### ISSUE TITLE
Toast is rendered behind keyboard on iOS

### ISSUE THREAD

**Issue by johakr** [prscX/react-native-toasty#2]
Would be great if the toast would be rendered above the keyboard on z or y axis.

**Comment by prscX** [comment]
Thanks @johakr for raising the issue and PR.

I have pushed release with [V0.0.4](https://github.com/prscX/react-native-toasty/releases/tag/v0.0.4). Can you please install and verify the same.

Please let me know in case you face any issues.

Thanks
</ Pranav >

**Comment by sachinB94** [comment]
@prscX Nope. Not fixed in v0.0.4.

React Native: v0.42.0
Device: iPhone 7 Plus (Simulator)
OS: iOS 11.4

**Comment by prscX** [comment]
@johakr: I believe it was done for Android only.

@sachinB94: Please feel free to share PR for the same.

Thanks
</ Pranav >
