### ISSUE TITLE
Toast at the top

### ISSUE THREAD

**Issue by Sin-** [prscX/react-native-toasty#3]
Hi, 
I have a tab navigation application and display a welcome message on login, but the toast is right on the tabs and you cannot navigate properly until the toast is gone.
My question is what should I do to make the toasts appear at the top of the screen instead of the bottom.

Thanks!

**Comment by vaqif14** [comment]
In IOS when keyboard enabled toast is not visible and i want too show toast at top

**Comment by oferRounds** [comment]
Any news on this one?

**Comment by prscX** [comment]
I have crossed checked android native library API's which we have integrated and I am afraid to share it does not positioning. If they come up with API then we can easily integrate the same. However on iOS they have API to support the same.

Thanks
</ Pranav >

**Comment by prscX** [comment]
I believe [crazycodeboy/react-native-easy-toast](https://github.com/crazycodeboy/react-native-easy-toast) which is JS implementation based supports position based renderer.

Thanks
</ Pranav >

**Comment by oferRounds** [comment]
@prscX  Got you! Thanks for the reply and details!

**Comment by oferRounds** [comment]
Please don’t move to JS implementation... JS implementations almost always fell not native...

**Comment by maihuuloi123** [comment]
this is a joke
